### ISSUE TITLE
Is wind mortality occurring even when wind speed are low?

### ISSUE THREAD

**Issue by rmscheller** [LANDIS-II-Foundation/Extension-Base-Hurricane#7]
The results suggest that mortality is ignoring the wind speed minimum.

**Comment by jameslamping** [comment]
Hi Rob, I tested the update on my test landscape and it looks like you fixed the mortality and low windspeeds issue. This now leads to a new issue. No matter how hard I push windspeeds up (right now my mode windspeed is 200 kph) I cannot get max windspeeds in active cells to be over the 60 kph threshold. I have set the coastline to be right up against the island I am using and to test on and speeds at coastline look ok to what I have set (180 - 200 kph) but max windspeed in active cells never seems to get up over 45 kph.

Something I noticed is that I don't have an expose class table in my input file so that might answer the lack of mortality change in areas of low exposure. I am adding that now! I have added my LANDIS log and  input file but below is what I am seeing for all storms.

2023-08-24 17:31:27,352 - Storm #1, **LandFallSpeed=203.0**, StormHeading=335.8, ClosestExposureKey=225
2023-08-24 17:31:31,342 -    Hurricane Not Sufficient to Cause Damage:  **MaxWS=45.642723589532**, HurricaneMinWS=60


 
[Landis-log.txt](https://github.com/LANDIS-II-Foundation/Extension-Biomass-Hurricane/files/12443461/Landis-log.txt)

**Comment by jameslamping** [comment]
I just tested the exposure classes table and it looks like the extension is not recognizing the table:

2023-08-25 14:24:32,423 - Error at line 52 of file "biomass_hurricane_AK.txt":
  Error reading input value for Maximum Degree:
    "ExposureClasses" is not a valid integer

[biomass_hurricane_AK.txt](https://github.com/LANDIS-II-Foundation/Extension-Biomass-Hurricane/files/12443660/biomass_hurricane_AK.txt)

**Comment by rmscheller** [comment]
James,

It seems that the documentation is lagging behind reality.  At some point, we eliminated the exposure classes table and we have a fixed set of exposures whereby:
switch (exposureIndex)
            {
                case 1:
                    return 0.1;
                case 2:
                    return 0.2;
                case 3:
                    return 0.3;
                case 4:
                    return 0.4;
                case 5:
                    return 0.5;
                case 6:
                    return 0.6;
                case 7:
                    return 0.7;
                case 8:
                    return 0.8;
                case 9:
                    return 0.9;

**Comment by jameslamping** [comment]
That makes sense! Thanks!
